version: '3.9'

services:

  manager:
    image: gpig:latest
    build: .
    command: /bin/sh ./manager/entrypoint.sh

  datagen-sim:
    image: gpig:latest
    build: .
    command: /bin/sh ./datagen/entrypoint.sh
    links:
      - manager

  api:
    image: gpig:latest
    build: .
    ports:
      - 8080:8080
    command: /bin/sh ./api/entrypoint.sh
    links:
      - manager
