version: '3.8'

services:

  manager:
    image: gpig:latest
    build: .
    command: /bin/sh ./manager/entrypoint.sh
    volumes:
      - ./configs/:/dyn-configs/

  datagen-sim:
    image: gpig:latest
    build: .
    command: /bin/sh ./datagen/entrypoint.sh
    links:
      - manager
    volumes:
      - ./configs/:/dyn-configs/

  api:
    image: gpig:latest
    build: .
    ports:
      - 8080:8080
    command: /bin/sh ./api/entrypoint.sh
    links:
      - manager
    volumes:
      - ./configs/:/dyn-configs/
