version: '3.8'

services:

  manager:
    image: gpig-manager:latest
    build:
      context: .
      dockerfile: ./manager/Dockerfile
    volumes:
      - ./configs/:/dyn-configs/

  datagen-sim:
    image: gpig-datagen:latest
    build:
      context: .
      dockerfile: ./datagen/Dockerfile
    links:
      - manager
    volumes:
      - ./configs/:/dyn-configs/

  api:
    image: gpig-api:latest
    build:
      context: .
      dockerfile: ./api/Dockerfile
    ports:
      - 8080:8080
    links:
      - manager
    volumes:
      - ./configs/:/dyn-configs/

  dashboard:
    image: gpig-dashboard:latest
    build:
      context: .
      dockerfile: ./dashboard/Dockerfile
    ports:
      - 3000:3000
