version: '3.8'

services:

  manager:
    image: gpig-manager:latest
    build:
      context: .
      dockerfile: ./manager/Dockerfile

  datagen-sim:
    image: gpig-datagen:latest
    build:
      context: .
      dockerfile: ./datagen/Dockerfile
    links:
      - manager
    depends_on:
      - manager

  sensor-service:
    image: gpig-sensor-service:latest
    build:
      context: .
      dockerfile: ./sensor_service/Dockerfile
    links:
      - manager
    depends_on:
      - manager

  api:
    image: gpig-api:latest
    build:
      context: .
      dockerfile: ./api/Dockerfile
    ports:
      - 8080:8080
    links:
      - manager
    depends_on:
      - manager
      - datagen-sim

  dashboard:
    image: gpig-dashboard:latest
    build:
      context: .
      dockerfile: ./dashboard/Dockerfile
    ports:
      - 80:3000
    depends_on:
      - api
