_ticks_per_second: 1.  # Only for the simulation loop
wts: 10  # Number of wind turbines
<<<<<<< HEAD
tick_freq: 60 * 60  # seconds
=======
tick_freq: 5 * 60  # seconds
>>>>>>> a2045fd191556978a21700759114494076ce13ee
# Wind
wind_mag_mean: 9.5  # metres / second
wind_mag_var: 7.0  # metres / second
wind_angle_jitter: 0.5  # 0 <= x <= 1
wind_mag_jitter: 0.5  # 0 <= x <= 1
# Waves
wind_to_wave_scalar: 0.7
wave_mag_var: 0.3
# Visibility
vis_mean: 1300.
vis_var: 400.
# Temp
temp_mean: 8.1  # degree Celsius
temp_jitter: 0.5  # 0 <= x <= 1
temp_annual_spread: 10.0  # degree Celsius
temp_daily_spread: 7.0  # degree Celsius0
temp_daily_std: 2.0  # degree Celsius.
temp_annual_std: 2.0  # degree Celsius.
# (outdated) Factor to convert between wind metres/sec and rotor rotations/sec
rotor_rps_alpha: 0.9998  # 0 <= x <= 1
rotor_rps_relative_var: 0.05
tower_vib_freq_mean: 4300.0  # Hz
tower_vib_freq_var: 240.0  # Hz
# Generator temperature
gen_temp_diff_mean: 2.0  # degree Celsius
gen_temp_diff_var: 0.5  # degree Celsius
# Data
history_length: 30
